.styleci.yml, composer.json, tests/unit/DbManagerTestCase.php, tests/unit/PhpManagerTest.php
* require-dev for psr/log as LogLevel is used in tests
* create our own ArrayTarget
=> Clean up dependencies

src/migrations/schema-mssql.sql
Adjusts indentations to match what is used by MS in MSSql docs and to show a bit clearer what is being done.
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | n/a
=> Improves readability

tests/EasyRule.php, tests/PhpManagerTest.php
=> add phpmanager tests

src/Item.php, src/Manager/BaseManager.php, src/Manager/PhpManager.php, tests/ExposedPhpManager.php
| Fixed issues  | 
- add type hints
- deleted duplicate code
=> Refactoring php manager

src/Item.php, src/ItemInterface.php, src/Manager/PhpManager.php, src/Rule.php, tests/ActionRule.php, tests/AuthorRule.php, tests/ManagerTestCase.php, tests/PhpManagerTest.php
| Fixed issues  | #24 
- add method 
- fix tests
- edit php manager
=> Add get attributes method

README.md
=> Add basic usage to readme file

README.md
=> Replace non-existent link

src/Item.php, src/Manager/PhpManager.php, tests/ManagerTestCase.php
=> Adding recursive role search

composer.json, src/Assignment.php, src/Exceptions/InvalidArgumentException.php, src/Exceptions/InvalidCallException.php, src/Exceptions/InvalidConfigException.php, src/Exceptions/RbacExceptionInterface.php
=> Remove useless dependency to FriendlyException, clean other

src/Assignment.php, src/DenyAll.php, src/Exceptions/InvalidArgumentException.php, src/Exceptions/InvalidCallException.php, src/Exceptions/InvalidConfigException.php, src/Exceptions/InvalidValueException.php, src/Exceptions/RbacExceptionInterface.php, src/Item.php, src/ItemInterface.php, src/Manager/BaseManager.php, src/Manager/PhpManager.php, src/ManagerInterface.php, src/Permission.php, src/Role.php, src/Rule.php, src/RuleFactory/ClassNameRuleFactory.php, src/RuleFactoryInterface.php, tests/ActionRule.php, tests/AuthorRule.php, tests/EasyRule.php, tests/ExposedPhpManager.php, tests/ManagerTestCase.php, tests/PhpManagerTest.php
=> Add declare(strict_types=1); #40

README.md
=> Grammar fixes of documentation

README.md
=> Fix example in documentation

README.md, composer.json, psalm.xml, src/Item.php, src/Manager.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
=> Adopt Psalm

src/Manager.php, src/StorageInterface.php
=> Fix phpdocs

README.md
=> Fix badged mutation README.md.

psalm.xml, src/Item.php, src/Manager.php, src/RuleFactory/ClassNameRuleFactory.php, src/RuleFactoryInterface.php
=> Set ErrorLevel 3 for Psalm

README.md, src/Manager.php, tests/ManagerTest.php, tests/ManagerWithOtherAssignmentStorageTest.php
=> Seperate storage into assigments and permissions/roles

phpunit.xml.dist, src/Manager.php, tests/ManagerTest.php
=> Deny assigning permission directly

README.md, src/Manager.php, tests/ManagerTest.php
| Breaks BC?    | ✔️/❌
| Fixed issues  | #76 
:warning: Merge after https://github.com/yiisoft/access/pull/13
=> Allow null value for access checking if user is guest

README.md, src/CompositeRule.php, tests/CompositeRuleTest.php, tests/EasyRule.php
=> Fix #69: Add CompositeRule

psalm.xml, src/AssignmentsStorageInterface.php, src/CompositeRule.php, src/Manager.php, src/RuleFactory/ClassNameRuleFactory.php, tests/FakeRolesStorage.php, tests/ManagerTest.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Psalm level 1, minor fixes

src/Assignment.php, src/DenyAll.php, src/Item.php, src/RuleFactory/ClassNameRuleFactory.php
=> Finalize classes and methods

src/Item.php
=> Improve psalm annotations

src/Manager.php, src/Rule.php, tests/RuleTest.php, tests/Support/AllowRule.php
=> Optional name for `Rule` constructor

src/CompositeRule.php, src/Item.php, src/Manager.php, src/RolesStorageInterface.php, src/Rule.php, src/RuleFactory/ClassNameRuleFactory.php, src/RuleFactoryInterface.php, src/RuleInterface.php, tests/CompositeRuleTest.php, tests/EasyRule.php, tests/FakeRolesStorage.php, tests/Support/AllowRule.php
=> Add `RuleInterface`

src/Manager.php, tests/ManagerTest.php
| Fixed issues  | #101
`setDefaultRoles()` → `setDefaultRoleNames()`
`getDefaultRoles()` → `getDefaultRoleNames()`
`getDefaultRoleInstances()` → `getDefaultRoles()`
Adopt PR: https://github.com/yiisoft/rbac-php/pull/36
=> Rename methods for get/set default roles

src/AssignmentsStorageInterface.php, src/Manager.php, tests/ManagerTest.php, tests/Support/FakeAssignmentsStorage.php
=> Fix #103: Refactor AssignmentsStorageInterface

src/CompositeRule.php, src/Manager.php
=> Fix #99: Allow int or stringable object as userId

README.md
=> Add hierarchy to readme

src/Manager.php, tests/ManagerTest.php
=> Implement fluent interface in `Manager`

src/Manager.php, tests/Exception/RuleInterfaceNotImplementedExceptionTest.php, tests/Exception/RuleNotFoundExceptionTest.php, tests/ManagerTest.php
=> Add tests + Minor CS improvements

src/Exception/ItemAlreadyExistsException.php, src/ItemsStorageInterface.php, src/Manager.php, tests/Exception/ItemAlreadyExistsExceptionTest.php, tests/ManagerTest.php, tests/Support/FakeItemsStorage.php
| Fixed issues  | #128 
Adopt PR: https://github.com/yiisoft/rbac-php/pull/46
=> Check item exists on add role or permission

tests/ManagerTest.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
=> Separate chain calls

CHANGELOG.md, composer.json, src/Exception/DefaultRoleNotFoundException.php, src/Manager.php
=> PR for #121: Add friendly exception when default roles are not found

.github/workflows/composer-require-checker.yml, CHANGELOG.md, composer.json, src/AssignmentsStorageInterface.php, src/Manager.php
Added composer-require-checker according to https://github.com/yiisoft/actions/pull/9
=> [Batch] Add composer-require-checker CI

CHANGELOG.md
=> Update CHANGELOG.md before 1.0.1 release

.gitattributes
=> Remove tests from .gitattributes

src/AssignmentsStorageInterface.php, src/ItemsStorageInterface.php
Related discussion - https://github.com/yiisoft/rbac-cycle-db/pull/60#discussion_r1287181997.
=> Move common Psalm types

README.md, src/CompositeRule.php
=> Actualize README and PHPDoc

tests/AssignmentsStorageTest.php, tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ItemsStorageTestTrait.php, tests/ItemsStorageTest.php, tests/Support/FakeItemsStorage.php
=> Test storages

CHANGELOG.md, src/AssignmentsStorageInterface.php, src/Manager.php, src/ManagerInterface.php, tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ManagerConfigurationTestTrait.php, tests/Support/FakeAssignmentsStorage.php
=> Improve handling and control of `Assignment::$createdAt`

src/ItemsStorageInterface.php
=> Revert `ItemsIndexedByName` psalm type

CHANGELOG.md, src/ItemsStorageInterface.php, tests/Common/AssignmentsStorageTestTrait.php
=> Fix changelog, psalm type and add not null check

src/ItemsStorageInterface.php
=> Change `ItemsIndexedByName` psalm type again

src/ItemsStorageInterface.php, src/Manager.php, tests/Support/FakeItemsStorage.php
=> Use more specific type hints

README.md
=> Add example of self-contained rule factory to docs

CHANGELOG.md, src/ItemsStorageInterface.php, tests/Support/FakeItemsStorage.php
=> Minor fixes and improve types

CHANGELOG.md
=> Update CHANGELOG [skip ci]

tests/bootstrap.php
=> Improve custom autoload

src/SimpleItemsStorage.php
=> Fixes after integrating simple items storage

CHANGELOG.md, src/Manager.php
=> Handle empty assignments in `Manager::getPermissionsByUserId()`

tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ItemsStorageTestTrait.php
=> Add option to recreate storages in tests

tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ItemsStorageTestTrait.php
=> Simplify recreation of storages in tests

.styleci.yml, src/Assignment.php
=> Revert changes with final method

tests/AssignmentTest.php, tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ItemsStorageTestTrait.php
=> Add test for adding item with past timestamps

src/Assignment.php, src/SimpleAssignmentsStorage.php, src/SimpleItemsStorage.php
=> Improve Psalm

CHANGELOG.md, src/SimpleAssignmentsStorage.php, tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ItemsStorageTestTrait.php
=> Add more tests to raise coverage in related packages

tests/Common/AssignmentsStorageTestTrait.php
=> Add test for removing non existing asslgnment

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, src/ItemsStorageInterface.php, src/Manager.php, src/SimpleItemsStorage.php, tests/Common/AssignmentsStorageTestTrait.php, tests/Common/ItemsStorageTestTrait.php
=> Rename access tree and improve coverage for db implementations

composer.json, tests/ConfigTest.php
=> Adjust for using with Yii Config

src/ManagerInterface.php
Thanks to @vjik for discovering.
=> Actualize `throws` PHPDOC tag for `ManagerInterface::assign()``
