src/DbManager.php
tests/unit/DbManagerTestCase.php
tests/unit/MySQLManagerCacheTest.php
tests/unit/MySQLManagerTest.php
tests/unit/PgSQLManagerCacheTest.php
tests/unit/PgSQLManagerTest.php

Fixed all tests.
I've removed from DbManager constructor parameters that can be null: logger and cache.
Instead I've added RuleFactoryInterface because it is required by BaseManager class
https://github.com/yiisoft/rbac/blob/f248a222e40cada07b6fcd8ebd93ca376ee882fd/src/BaseManager.php#L44

Fixed all tests

---

src/Manager/PhpManager.php

| Fixed issues  | fixed package update problem
"Non-static method Yiisoft\VarDumper\VarDumper::export() should not be called statically"

Fix var dumper

---

src/ItemsStorageInterface.php
src/Manager.php
tests/Support/FakeItemsStorage.php

| Fixed issues  | #110
Adopt PR: https://github.com/yiisoft/rbac-php/pull/41

Replace `getAllChildren()` to `getParents()` in `ItemsStorageInterface`

---

CHANGELOG.md
src/Manager.php
src/ManagerInterface.php
tests/Common/ManagerLogicTestTrait.php

Exclude parent role from `Manager::getAllChildRoles()`

---

tests/Support/FakeItemsStorage.php

Refactor `FakeItemsStorage::hasChild()` (sync with `rbac-php`)

---

CHANGELOG.md
src/Manager.php
src/ManagerInterface.php
tests/Common/ManagerConfigurationTestTrait.php
tests/Common/ManagerLogicTestTrait.php

Do not use storages directly

---

CHANGELOG.md
src/ItemsStorageInterface.php
src/Manager.php
tests/Common/ItemsStorageTestTrait.php
tests/Support/FakeItemsStorage.php

Optimize calls for getting child items within the loops

---

tests/Support/FakeItemsStorage.php

Improve filtering of items

---

src/ItemsStorageInterface.php

Change non-empty-string to string in Psalm type for `AccessTree`

---

.github/workflows/build.yml
.github/workflows/composer-require-checker.yml
.github/workflows/rector.yml
.github/workflows/static.yml
.scrutinizer.yml
CHANGELOG.md
composer.json
phpunit.xml.dist
tests/Common/AssignmentsStorageTestTrait.php
tests/Common/ItemsStorageTestTrait.php
tests/Common/ManagerLogicTestTrait.php
tests/CompositeRuleTest.php
tests/bootstrap.php

Bump PHP version to 8.1 and PHPUnit version to 10.5.2

---

src/Manager.php
src/SimpleAssignmentsStorage.php

Make SimpleAssignmentsStorage::$assignments protected

---

CHANGELOG.md
src/SimpleItemsStorage.php
tests/Common/ItemsStorageTestTrait.php

Exclude items with start names when getting children

---

tests/Common/ItemsStorageTestTrait.php
tests/Common/ManagerLogicTestTrait.php

Related - https://github.com/yiisoft/rbac-cycle-db/issues/72.

Use manager for adding items in tests

---

CHANGELOG.md
src/Item.php
tests/Common/AssignmentsStorageTestTrait.php
tests/Common/ItemsStorageTestTrait.php
tests/Common/ManagerLogicTestTrait.php
tests/PermissionTest.php
tests/RoleTest.php

Related - https://github.com/yiisoft/rbac-cycle-db/issues/77.

Use snake case for item attribute names (ease migration from Yii 2)

---

CHANGELOG.md
src/Assignment.php
src/Item.php
tests/AssignmentTest.php

Add `Assignment::getAttributes()` method

---

CHANGELOG.md
src/SimpleItemsStorage.php
tests/Common/ItemsStorageTestTrait.php

Concurrency in items storage tests, handle not found base item in access tree

---

.github/workflows/bc.yml
.github/workflows/build.yml
.github/workflows/composer-require-checker.yml
.github/workflows/mutation.yml
.github/workflows/rector.yml
.github/workflows/static.yml
src/ItemsStorageInterface.php
src/ManagerInterface.php
src/SimpleItemsStorage.php
tests/Common/ItemsStorageTestTrait.php

Add tests for access tree

---

CHANGELOG.md
README.md
src/Assignment.php
src/AssignmentsStorageInterface.php
src/CompositeRule.php
src/ItemsStorageInterface.php
src/Manager.php
src/ManagerInterface.php
src/RuleContext.php
src/RuleInterface.php
src/SimpleAssignmentsStorage.php
src/SimpleItemsStorage.php
tests/Common/AssignmentsStorageTestTrait.php
tests/Common/ItemsStorageTestTrait.php
tests/RuleContextTest.php
tests/Support/EasyRule.php
tests/Support/SimpleRuleFactory.php

Minor fixes

---

CHANGELOG.md
src/Manager.php
tests/Common/ManagerLogicTestTrait.php

Return `$this` instead of throwing "already assigned" exception in `Manager::assign()`

---

CHANGELOG.md
README.md
src/CompositeRule.php
src/RuleInterface.php
tests/Support/AdsRule.php
tests/Support/AuthorRule.php
tests/Support/BanRule.php
tests/Support/FalseRule.php
tests/Support/GuestRule.php
tests/Support/SubscriptionRule.php
tests/Support/TrueRule.php
tests/Support/WannabeRule.php

Thanks to @vjik for discovering.

Actualize rule example in docs, rename `$ruleContext` to `$context`

---

CHANGELOG.md
src/Manager.php
tests/Common/ManagerLogicTestTrait.php

Reported by @vjik. Unable to reproduce.

Test new case for `Manager::userHasPermission()`

---

CHANGELOG.md
src/Manager.php
src/ManagerInterface.php
tests/Common/ManagerLogicTestTrait.php

Additions to PR 263

---

CHANGELOG.md
composer.json
src/Manager.php
tests/Common/AssignmentsStorageTestTrait.php
tests/Common/ItemsStorageTestTrait.php
tests/Common/ManagerConfigurationTestTrait.php
tests/Common/ManagerLogicTestTrait.php

Add optional `$clock` parameter to `Manager` constructor

---

.github/workflows/bc.yml
.github/workflows/build.yml
.github/workflows/composer-require-checker.yml
.github/workflows/mutation.yml
.github/workflows/rector.yml
.github/workflows/static.yml
CHANGELOG.md
composer.json
psalm.xml
rector.php

PHP 8.4 support
